version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: pr
      POSTGRES_USER: root
      POSTGRES_PASSWORD: proot
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
      - DATABASE_URL=postgresql://root:root@db:5432/pr

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
